export const defaults = {
    data: [],
    dataIndex: 0,
    direction: 'clockwise',
    isDragging: () => {},
    keypressStep: 1,
    knobAnimated: true,
    knobColor: '#48b400',
    knobDraggable: true,
    knobHide: false,
    knobHideRing: false,
    knobPosition: 'top',
    knobRingRadius: 0.45,
    knobSize: 36,
    label: 'ANGLE',
    labelAppendCss: null,
    labelAppendValue: '',
    labelBottom: false,
    labelColor: '#333',
    labelFontSize: '1rem',
    labelHideValue: false,
    labelHorizontalOffset: null,
    labelPrependCss: null,
    labelPrependValue: '',
    labelShow: true,
    labelValueFontSize: '3rem',
    labelValueHorizontalOffset: null,
    labelValueVerticalOffset: null,
    labelVerticalOffset: null,
    limitDragRange: false,
    max: 359,
    min: 0,
    onChange: () => {},
    progressColorFrom: '#81c784',
    progressColorTo: '#006403',
    progressLineCap: 'round',
    progressSize: 16,
    trackColor: '#DDDEFB',
    trackDraggable: false,
    trackGradient: null,
    trackSize: 16,
    value: null,
    width: 280,
};
